const data = [
  {
    h5: "Feedback positif",
    p: "Simple, rapide et efficace ! Une équipe à l'écoute ! Je recommande vivement !",
    spanRate: "5.0",
    spanName: "@Robin Mourier",
    spanDate: "2023-09-19",
  },
  {
    h5: "Super expérience",
    p: "Sérieux, à l’écoute et très disponible je recommande fortement cette entreprise les yeux fermés !!!",
    spanRate: "5.0",
    spanName: "@Wady Talhaoui",
    spanDate: "2023-09-18",
  },
  {
    h5: "Aide inestimable",
    p: "Excellente expérience humaine vécue avec Tristan de Siko qui me guidera sur chaques routes ! Merci encore 🙏",
    spanRate: "5.0",
    spanName: "@Youssouf SANOGO",
    spanDate: "2023-09-17",
  },
  {
    h5: "Recommandation sincère",
    p: "Tres bonne expérience, tres accueillant et a l'écoute. Je recommande pour les solutions de financement 😁😁",
    spanRate: "5.0",
    spanName: "@Kevin Vital",
    spanDate: "2023-09-16",
  },
  {
    h5: "Professionnalisme au top",
    p: "Société très professionnel,et réactive Tres bonne communication 👌",
    spanRate: "5.0",
    spanName: "@Rak",
    spanDate: "2023-09-15",
  },
  {
    h5: "Service incroyable",
    p: "Je recommande a 100%. En quelques mots : Rapide, efficace et c’est un plaisir d’échanger avec eux par téléphone 😊",
    spanRate: "5.0",
    spanName: "@Manelle BC",
    spanDate: "2023-09-14",
  },
  {
    h5: "Feedback honnête",
    p: "Très bonne expérience, bonne communication, personnel disponible et réactif m, je recommande.",
    spanRate: "5.0",
    spanName: "Yves-Roland BATAMIO",
    spanDate: "2023-09-13",
  },
  {
    h5: "Merci pour l'aide",
    p: "Merciii pour l assistance apporter de l équipe et aux employer qui sont à l écoute et font tout pour nous aider merci encor et à bientôt",
    spanRate: "4.0",
    spanName: "@Kebaili Hacen",
    spanDate: "2023-09-12",
  },
  {
    h5: "Prestation excellente",
    p: "Top , Je recommande Siko Mobility pour leur professionnalisme. Tristan D’Halluin et au top très à l’écoute du client . 👌",
    spanRate: "5.0",
    spanName: "@Quentin Berthe",
    spanDate: "2023-09-11",
  },
  {
    h5: "Bonne expérience",
    p: "Équipe disponible et professionnel, un grand merci !",
    spanRate: "4.0",
    spanName: "@Arthur Joseph",
    spanDate: "2023-09-10",
  },
];
